In [1]:
import torch
import numpy as np

### Pytorch Tensors.

They are the data structures we use when programming with neural networks.
The first actions we take are data preprocessing routines that convert our data to tensors that will be fed into our neural network.
Tensors in Pytorch are represented using the **torch.Tensor** class.

In [3]:
# Create a torch tensor using a class constructor:
t = torch.Tensor()
print(t)
type(t)

tensor([])


torch.Tensor

Apart from the basic tensor attributes we discussed earlier, there are specific pytorch tensor attributes that deal with pytorches implementations.
These are:  
- Datatype
- Device
- Layout

In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


##### Datatype
The datatype (.float32) specifies the *type* of data that is stored within the tensor.Tensors contain uniform (of the same type) numerical data with one of these types: 

<div style="text-align: center;">

![image_a](Img\data_types.JPG) 

</div>

> Tensors have a CPU and a GPU version.   
> **Tensor operations between tensors must happen with tensors of the same datatype**

##### Device
The .device(), (which is cpu in our case), specifies the device where the tensor data is allocated. This determines where the computations for the given tensor will be performed.
Pytorch supports the use of multiple devices.

In [5]:
# Specify the device:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

From this output, we can see that the device is *cuda*, which means the device is a cpu and the index=0 tells us that its the *first gpu that we have*.
> If we specify cuda:1 or 2 or 3 etc. and we don't actually have 2 or more gpus we would get an error.  
> **Tensor operations between tensors must happen between tensors *that exist on the same device*.**

##### Layout
Our layout is .strided
It tells us how our tensors data is layed out in memory. For now we consider it as default and there is no need to change it for now.

 Take away from the tensor attributes

As neural network programmers, we need to be aware of the following:

    Tensors contain data of a uniform type (dtype).
    Tensor computations between tensors depend on the dtype and the device.


##### Examples.

• Datatype

In [9]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])
print(f't1 data type is: {t1.dtype}')
print(f't2 data type is: {t2.dtype}')

t1 data type is: torch.int64
t2 data type is: torch.float32


• Computation between datatypes

In [10]:
t1 + t2

tensor([2., 4., 6.])

• Same process, with the device.

In [11]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

• Check the device the tensors are allocated on.

In [14]:
t1.device
t2.device
print(f't1 is on: {t1.device}')
print(f't2 is on: {t2.device}') # It doesn't show index=0 probably because I have only one gpu.

t1 is on: cpu
t2 is on: cuda:0


In [15]:
# Example computation
t1 + t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

The above error is quite self explanatory: Pytorch can't do computations between tensors that "live" on different devices.

##### Ways of creating Tensors from data.
These are the primary ways of creating tensor objects (instances of the torch.Tensor class), with data (array-like) in PyTorch:
1. torch.Tensor(data)
2. torch.tensor(data)
3. torch.as_tensor(data)
4. torch.from_numpy(data)

In [16]:
# Create data using a numpy array
data = np.array([1,2,3])
type(data)

numpy.ndarray

>We will use the above array to create a tensor using the 4 different ways.
>They all accept array-like structures like numpy arrays and give us instances of the pytorch tensor class.

1. The numpy array we created, has integers. The .Tensor() is a  class constructor  that returns floating point.

In [17]:
torch.Tensor(data)

tensor([1., 2., 3.])

2. The lowercase .tensor() is a function (factory function) that builds tensor objects.
Here the datatype **maches the input data** of the numpy array we created.

In [19]:
torch.tensor(data) 

tensor([1, 2, 3], dtype=torch.int32)

3. as_tensor()

In [21]:
torch.as_tensor(data) # Notice the output is the same as the .tensor factory function.

tensor([1, 2, 3], dtype=torch.int32)

4. torch.from_numpy() gives the same outpus as 2 and 3.

In [22]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

> The oddball here is the .Tensor() class constructor. All the others behave seemingly in the same way.

##### Creating tensors without data

1. ***The identity tensor/matrix***.
To call this function, we just specify the number of rows we want. (Ones down the diagonal and zeros everywhere else.)    

**torch.eye(number of rows)**

In [23]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

2. ***Zeros function***  
When we call it we specify the length of each axis.

**torch.zeros(rows, columns)**

In [29]:
torch.zeros(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

3. ***Ones function***  
As above, except returns 1.

In [30]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

4. **Randomized values.**

In [2]:
torch.rand(2,2)

tensor([[0.4955, 0.3439],
        [0.5842, 0.4087]])

> **Main takeaway:** We can either create tensors using pre-existing data, or we can do it using predefined functions for common data values like 0,1 or randoms.