In [2]:
import torch

#### *Intro*

Tensor operation types:
1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

#### *1. Reshaping operations*

Suppose we have the following tensor:

(***In PyTorch the size and shape of a tensor mean the same thing.***)

In [3]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


The shape of this tensor is (3 x 4).  
This allows us to see that this is a **rank 2 tensor** (*we need 2 indexes to acces a single element*) with **two axes**.  
The first axis, has a length of **3** and the second axis has a length of **4**.

• The elements of the first axis ($Τ_{ij},  i=[1,3]$), are **arrays**:


![arrays](Img/arrays.JPG)


• The elements of the second axis ($T_{ij}, j = [1,3]$), are **numbers**:

![numbers](Img/numbers.JPG)

In pytorch there are two methods to access the shape:
1. We can use the size method.
2. We can use the shape attribute.

In [4]:
t.size()

torch.Size([3, 4])

In [5]:
t.shape

torch.Size([3, 4])

We can obtain the tensors rank by checking the *length of its shape*:

In [6]:
len(t.shape)

2

Another important feature that tensor shape gives us is *the number of elements* contained within the tensor. This can be deduced by taking the product of the component values in the shape. ($i x j$)

• We can *convert the shape to a tensor* and then ask for the *product* to see that the tensor contains 12 components. (Sometimes referred to as the scalar components of the tensor)

In [7]:
torch.tensor(t.shape).prod()

tensor(12)

• We can also use another function that is specially designed for this purpose, called *numel*, which is short for **number of elements**.

In [8]:
t.numel()

12

>In terms of reshaping we care about the number of elements. Since our tensor has 12 elements, any reshaping must account for all 12 of these elements. (**reshape doesn't change the underlying data**)

*How to reshape without changing the rank:*

Notice how all of the shapes have to account for the number of elements in the tensor :  
**rows * columns = 12 elements**

In [72]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [83]:
# verify shape
t.reshape(1,12).shape

torch.Size([1, 12])

In [74]:
# verify rank (ndimentions) its 2 dimentional: row 0, colums 12.
t.dim()

2

In [71]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [70]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [82]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [56]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [64]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [75]:
# verify shape
t1 = t.reshape(12,1)
t1.shape

torch.Size([12, 1])

In [81]:
# verify rank (ndimentions) its 2 dimentional 12 rows x 1 column
t1 = t.reshape(12,1)
t1.dim()

2

In [80]:
# verify rank using len()
len(t1.shape)

2

We can change the rank by adding another dimention:

In [85]:
# for example (random variable, rows, colums)
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

*Notice [[[   ]]] that shows the rank or the dimentions of the tensor*. We need 3 indexes to acces each element : random variable, row, column

The next way to change the shape of a tensor is **squeezing and unsqueezing**  
Squeezing *removes all the axis that have a length of one*  
Unsqueezing *adds a dimention with a length of one*

These functions allow us to expand or shrink the rank of our tensor

In [91]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


*notice tensor([[......]]) shows its a 2D tensor*

In [93]:
# Squeeze
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


*notice tensor([.....]) shows its a 1D tensor now after squeezing the axis or length of one*

In [94]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


*the tensor is back to 2D after specifying dimention = 0 to be added as having a length of 1*

Lets look at a very common usecase for squeezing a tensor by building a flatten function.  
*(flatten = turn it into a lower rank tensor)*  
Flatten means to remove all of the axes except for one, which creates another tensor with a single axis which contains the *elements* of the tensor. So essentially we create a 1D array that contains all of the scalar components of the tensor.
> A flatten operation is an operation that must occur inside a neural network, when we transition from a convolutional layer to a fully connected layer.

We take the output from the convolutional layer (in the form of output channels):  

![single_output](Img/single_output.JPG)

An we flatten these channels into a single 1D array:

![flattened](Img/flattened.JPG)

#### Implement flatten from scratch:

A single dimension may be -1, in which case it’s inferred from the remaining dimensions and the number of elements in input.

In [95]:
def flatten(t): # Take a tensor t as argument
    t = t.reshape(1,-1) 
    t = t.squeeze()
    return t

Since the input tensor can be any shape, we pass -1 for the second argument of the reshape function. With pytorch, **-1** tells **reshape()** to figure out what the value should be, based on the other value and the number of elements contained within the tensor. Since our tensor has 12 elements, reshape() will be able to figure out that a 12 is required for the length of the second axis to ensure that there is enough room for all the elements after reshaping.

Example:

In [96]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

After squeezing, the first axis is removed and we obtain our desired result:  

![flatten_example](Img/flatten_example.JPG)

*Other ways of flattening using only reshape function*

In [98]:
t.reshape(-1)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [99]:
t.reshape(1,-1)[0]

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [101]:
t = t.reshape(12)
print(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [104]:
t = t.reshape(t.numel())
print(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


#### *Concatenating Tensors*

We combine tensors using the **cat()** function, and the resulting tensor will have a shape that depends on the shape of the two input tensors. 

In [115]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

print(t1)
print(t1.size())
print(f't1 rank: {len(t1.shape)}') # Rank is the length of its shape
print('-------')
print(t2)
print(t2.size())
print(f't2 rank: {len(t2.shape)}') # Rank is the length of its shape

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
t1 rank: 2
-------
tensor([[5, 6],
        [7, 8]])
torch.Size([2, 2])
t2 rank: 2


We can combine t1 and t2 row-wise (dimention/axis-0) in the following way:

![cat_dim0_rows](Img/cat_dim0_rows.JPG)

In [116]:
t3 = torch.cat((t1,t2), dim=0)
print(t3)
print(t3.size())
print(f't3 rank: {len(t3.shape)}') # Rank is the length of its shape


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
t3 rank: 2


We can combine them *column-wise* (dim/axis1) like this:

![cat_dim1_columns](Img/cat_dim1_columns.JPG)

In [117]:
t4 = torch.cat((t1,t2), dim=1)
print(t4)
print(t4.size())
print(f't4 rank: {len(t4.shape)}') # Rank is the length of its shape


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
torch.Size([2, 4])
t4 rank: 2
